# Generated by Django 4.2.7 on 2025-09-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('issue_number', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('labels', models.JSONField()),
                ('type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
